go_back_n:
	@gcc go_back_n.c -lm
	@./a.out

selective_repeat:
	@gcc selective_repeat.c -lm
	@./a.out

stop_and_wait:
	@gcc stop_and_wait.c -lm
	@./a.out

clean:
	@rm *.out

.PHONY: clean
